# A. Bag of Words

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({'text': ['people watch campusx','campusx watch campusx', 'people write comment', 'campusx write comment'], 'output': [1,1,0,0]})

In [3]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [8]:
# !pip3 install scikit-learn
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

In [11]:
bow = cv.fit_transform(df['text'])

cv.vocabulary_

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}

In [14]:
bow[0].toarray()

array([[1, 0, 1, 1, 0]])

In [16]:
cv.transform(['people watch and write comment of campusx']).toarray()

array([[1, 1, 1, 1, 1]])

# B. n-grams 

In [22]:
cv = CountVectorizer(ngram_range=(1,2))

bow = cv.fit_transform(df['text'])

cv.vocabulary_

{'people': 4,
 'watch': 7,
 'campusx': 0,
 'people watch': 5,
 'watch campusx': 8,
 'campusx watch': 1,
 'write': 9,
 'comment': 3,
 'people write': 6,
 'write comment': 10,
 'campusx write': 2}

# C. TF-IDF

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
tfidf.fit_transform(df['text'])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 11 stored elements and shape (4, 5)>

In [25]:
tfidf.vocabulary_

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}

In [26]:
tfidf.idf_

array([1.22314355, 1.51082562, 1.51082562, 1.51082562, 1.51082562])

In [27]:
tfidf.get_feature_names_out()

array(['campusx', 'comment', 'people', 'watch', 'write'], dtype=object)

# D. Word2Vec

In [39]:
# !pip3 install gensim

import gensim
from gensim.models import Word2Vec, KeyedVectors

ModuleNotFoundError: No module named 'gensim'

In [37]:
# brew install wget -> in terminal

!wget -c "https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz"

--2024-12-25 16:46:02--  https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.217.138.232, 16.15.184.21, 54.231.193.248, ...
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.217.138.232|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-12-25 16:46:03 ERROR 404: Not Found.

